mydb/urls.py
from django.conf.urls import url, include
from mydb import views

app_name = 'mydb'

urlpatterns = [
    url(r'^$', views.front, name='front'),
    url('accounts', views.vault, name='vault'),
    url('formpage', views.form_name_view, name='form_name'),
    url('user', views.users_, name='index_urls'),
    url('signup', views.register, name='signup'),
]

mypassvault/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from mydb import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url('myvault/', include('mydb.urls')),
    url(r'user_login', views.user_login, name='login'),
    url(r'user_logout', views.user_logout, name='logout'),
    path('admin/', admin.site.urls),
]

mydb/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Topic(models.Model):  # inheriting from models --- Topic is Service field in Database
    topic_name = models.CharField(max_length=200)

    def __str__(self):
        return self.topic_name


class Account(models.Model):  # this will handle the Website Name and URL
    topic = models.ForeignKey(Topic, on_delete=models.DO_NOTHING)  # Service in database
    Email = models.CharField(max_length=100)  # Email in database
    website_name = models.CharField(max_length=100)  # website_name in database
    url = models.URLField(unique=False)  # website in database
    password = models.CharField(max_length=100)
    userName = models.CharField(max_length=100)
    comment = models.CharField(max_length=1500)
    Name = models.CharField(max_length=100)
    Address = models.CharField(max_length=250)  # Address in database
    Phone_Number = models.CharField(max_length=25)  # Phone Number in database

    def __str__(self):
        return self.url


class AccessRecord(models.Model):
    name = models.ForeignKey(Account, on_delete=models.DO_NOTHING)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


##########################################################################
# Creating User Model                                                    #
##########################################################################

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username


##########################################################################
# Creating User Model                                                    #
##########################################################################

mydb/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from mydb.models import UserProfileInfo


class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verifyemail = forms.EmailField(label='Enter Your Email Again')
    text = forms.CharField(widget=forms.Textarea)
    bot_catcher = forms.CharField(required=False, widget=forms.HiddenInput,
                                  validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verifyemail']

        if email != vmail:
            raise forms.ValidationError("E-mails don't match")


##########################################################################
# Form for Sign up Page! mydb/signup.html                                #
##########################################################################

class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'
        widgets = {
            'user_name': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.TextInput(attrs={'class': 'form-control', 'type': 'password'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'email@example.com'}),
        }

    def clean(self):
        all_clean_data = super().clean()
        _user = all_clean_data['user_name']

        # Check to see if any users already exist with this email as a username.
        try:
            match = User.objects.get(user_name=_user)
            if str(match) == str(_user):
                print('User Already Exist')
                raise forms.ValidationError('This Username is already in use.')
        except User.DoesNotExist:
            # Unable to find a user, this is fine
            pass


####################################################################################
# Form for Sign up Page! mydb/signup.html  using django.user.auth built in manager #
####################################################################################

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

mydb/views.py
from django.shortcuts import render
from django.http.request import HttpRequest
from mydb.models import Account
from mydb import forms
from mydb.forms import UserProfileInfoForm, UserForm
from django.contrib import admin
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponsePermanentRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def index(request):
    return render(request, 'mydb/index.html')


def front(request):
    return render(request, 'mydb/front.html', context=None)


def vault(request):
    accounts_list = Account.objects.order_by('url')
    passwords = {"accounts": accounts_list}
    return render(request, 'mydb/accounts.html', context=passwords)


def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)
        if form.is_valid():
            # do something
            print("validation Success")
            print(form.cleaned_data['name'])
            print(form.cleaned_data['email'])
            print(form.cleaned_data['text'])

    return render(request, 'mydb/form.html', context={'form': form})


##########################################################################
# View that handles request to See signup.html                           #
##########################################################################


def users_(request):
    # passwords = {"accounts": accounts_list}
    return render(request, 'mydb/index.html')


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'mydb/signup.html',
                  context={'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})


##########################################################################
#                            LOGIN SECTION                               #
# View that handles request to See login.html                            #
##########################################################################

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponsePermanentRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("False Login")
            return HttpResponse("Invalid Login credentials ")

    else:
        return render(request, 'mydb/login.html', {})


##########################################################################
#                            LOGOUT SECTION                               #
# View that handles request to See logout.html                            #
##########################################################################

@login_required
def user_logout(request):
    logout(request)
    return HttpResponsePermanentRedirect(reverse('index'))

templates/mydb/accounts.html
<!DOCTYPE html>


{% extends "mydb/base.html"%}
    {%load static%}
    {%block body_block%}
    <style>
        .container{
            width=87%;
        }
    </style>
    <title>MyVault</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/account_style.css" %}">
   <section>
      <h1>MyVault</h1>
    </section>

    <div class="container-fluid">
        <div class="djangolist" align="center">
        {% if accounts %}
            <p> There's {{ accounts|length }} Account(s) stored</p>
            <table class="content-table" >
                <thead>
                    <tr>
                        <th>Url </th>
                        <th>User Name </th>
                        <th>Password</th>
                        <th>Service</th>
                    </tr>
                </thead>
                {% for acc in accounts %}
                    <tr>
                        <td> <div> {{acc.url}} </div> </td>
                        <td> <div>{{acc.userName}} </div></td>
                        <td> <div>{{acc.password}} </div></td>
                        <td> <div>{{acc.topic}} </div></td>

                    </tr>

                {% endfor %}
            </table>

        {% endif %}

    </div>
    </div>
    {%endblock%}

templates/mydb/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <style>
        .container{
            box-shadow: 0px 0px 10px 10px rgba(0, 0, 0, 0.04);
        }
        h1,h2 {
            text-align: center;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">MyPassVault</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                  {% endif %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Dropdown
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
              </ul>
              <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
    </nav>

    <div class="container">
        {% block body_block %}
<!--        Here goes the inherited content-->
        {%endblock%}
    </div>


</body>
</html>

templates/mydb/form.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forms</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet"  href="{% static "css/forms.css" %}">
</head>
<body>
    <h1 align="center">Form #1</h1>
    <div class="container">
        <form method="POST">
            {{form.as_p}}
            {%csrf_token%}
            <input type="submit" class="btn btn-primary" value="submit">

        </form>

    </div>
</body>
</html>

templates/mydb/front.html
<!DOCTYPE html>

{% extends "mydb/base.html"%}
    {%block body_block%}
        <div class="jumbotron">
          <h1 class="display-4" align="center">Welcome to MyPassVault Version 1.0</h1>
          <p class="lead" align="center">Enjoy our Open Source Project</p>
          <hr class="my-4">
          <p align="center">This Project was created to provide an OpenSource Option to safely store your passwords without having to depend
              On third party companies</p>
          <center><a class="btn btn-primary btn-lg" href="accounts.html" role="button">Show me My Passwords</a></center>
        </div>
        <h1>Welcome to Index page</h1>
        <h2>This is index.html page showing</h2>
    {%endblock%}

templates/mydb/index.html
<!DOCTYPE html>
{% extends "mydb/base.html" %}
    {% block body_block %}
        <div class="jumbotron">
      <h1 class="display-4" align="center">Welcome to Vault Pass</h1>
      <p class="lead" align="center">You can register here</p>
      <hr class="my-4">
      <p align="center">This Project was created to provide an OpenSource Option to safely store your passwords without having to depend
          On third party companies</p>
      <center><a class="btn btn-primary btn-lg" href="{% url 'mydb:signup' %}" role="button">Sing up</a></center>
    </div>
    {% endblock %}

templates/mydb/login.html
<!DOCTYPE html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
{% extends 'mydb/base.html' %}

{% block body_block%}
    <h1> Login</h1>
    <form class="form-group" action="" method="POST">
        {%csrf_token%}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
        <br>
        <label for="password">Password:</label>
        <input type="text" name="password">
        <br>
        <input type="submit" name="" value="Login">
    </form>


{% endblock %}

templates/mydb/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logout</title>
</head>
<body>

</body>
</html>

templates/mydb/signup.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MyPassVault - Sign up</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/sign_up_style.css' %}">
</head>
<body>
    <main>
<!--        <h1 align="center">Please Sign up here!</h1>-->

        <section class="container">

            <div class="container-shadow">
                <div class="nav-box">
                    <div class="logo-container">
                        <img src="https://i.ibb.co/tJbfTs1/vault-icon.png" alt="logo">
                        <h4 class="logo">MyPassVault</h4>
			        </div>
                    <nav>
                        <ul class="nav-links">
                            <li > <a class="nav-link" href="#">Support</a></li>
                            <li > <a class="nav-link" href="#">Services</a></li>
                            <li > <a class="nav-link" href="#">Log in</a></li>
                        </ul>
			        </nav>
                </div>
                <div class="cta">


                        {% if registered%}

                                <h1>Thank you for registering!</h1>

                             <div class="container-small">
                                <div class="introduction">
                                    <div class="intro-text">
                                        <h1>Why register?</h1>
                                        <p>
                                            At MyVault we believe that the only person that should have access to your
                                            most valued information and privacy is YOU and only YOU!
                                        </p>
                                        <p>
                                            All your information is password encrypted and only you will be able to access this
                                            Website.
                                        </p>
                                     </div>
                                      <div class="cover">

                                          <center><img src="https://i.ibb.co/W5qjXpW/world.png" alt="world" border="0"></center>
                                      </div>
                                 </div>
                            </div>
                        {%else%}

                            <form class="myform" enctype="multipart/form-data" method="post">
                                <h2>Register As a Myvault User</h2>
                                {{user_form.as_p}}
                                {{profile_form.as_p}}
                                {% csrf_token %}
                                <input type="submit" class="cta-register" value="Register">
                            </form>

                            <div class="container-small">
                                <div class="introduction">
                                    <div class="intro-text">
                                        <h1>Why register?</h1>
                                        <p>
                                            At MyVault we believe that the only person that should have access to your
                                            most valued information and privacy is YOU and only YOU!
                                        </p>
                                        <p>
                                            All your information is password encrypted and only you will be able to access this
                                            Website.
                                        </p>
                                     </div>
                                      <div class="cover">

                                          <center><img src="https://i.ibb.co/W5qjXpW/world.png" alt="world" border="0"></center>
                                      </div>
                                 </div>
                            </div>
                        {%endif%}


                </div>

            </div>
         </section>
    </main>
</body>
</html>

templates/mydb/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users</title>
</head>
<body>

</body>
</html>